.script:
  script:
    - |
      julia --project=@. -e '
        run(`git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"`)
        using Pkg
        pkg"registry add git@gitlab.com:tensors4fields/tensors4fieldsregistry.git"
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
Julia 1.6:
  image: julia:1.6
  extends:
    - .script
    - .coverage
Julia 1.7:
  image: julia:1.7
  extends:
    - .script
    - .coverage
Julia 1.8:
  image: julia:1.8
  extends:
    - .script
    - .coverage
pages:
  image: julia:1.6
  stage: deploy
  script:
    - |
      julia --project=docs -e '
        using Pkg
        pkg"registry add git@gitlab.com:tensors4fields/tensors4fieldsregistry.git"
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using TCIalgorithms
        doctest(TCIalgorithms)
        include("docs/make.jl")'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - main
